name: tasks
description: A library to create, read, edit & delete Tasks from the Google Tasks API.
version: 1.0.0
homepage: https://github.com/berkobob/tasks
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  logger:
    git:
      url: https://github.com/berkobob/logger 
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
